### ISSUE TITLE
Vivado version conflict

### ISSUE THREAD

**Issue by QGrain** [GabrielElkadiki/Ethernet-Stopwatch#1]
@GabrielElkadiki 
Your script is writen for <vivado 2016.3>.  How could I run it on <vivado 2018.1>?
In a Hurry, Thanks a lot for your reading!

**Comment by GabrielElkadiki** [comment]
I'm not entirely confident its possible without vivado 2016, I'd need to open the project using 2018 and then regenerate the scripts.

If you're short on time, I recommend installing Vivado 2016 and using that to run the script to produce a Vivado 2016 project and then open the project using Vivado 2018.

Last time I tried that however my block diagram did not build correctly at all.

Are you able to run the design1.tcl script on its own?

**Comment by QGrain** [comment]
Well I get it. Thanks a lot :)

Actually I have tried to modify the .tcl script by replacing words like "2016" with "2018" ...... but it doesn't work haha.

BTW, this project is really fantastic!

**Comment by GabrielElkadiki** [comment]
Thank you! 
I need to work on my master controller though since its quite bulky and uses up way more space than it needs to. The TCP/IP communication is also a little inefficient currently. Hope you're able to get it running!
